### ISSUE TITLE
Can't compile Bin2AsciiLevel1 

### ISSUE THREAD

**Issue by ceruleo-dev** [jgte/grace-data#4]
Hi!
first of all thanks for these sets of scripts, they are really useful!
After setting my secret.txt file and running the update.sh script to compile the BIN to ASCII converter, I run into the following issues:

```
/usr/bin/ld: lib/lib.a(InitializeHeaders.o):(.bss+0x0): multiple definition of `FileHeaderLabel'; /tmp/ccpIOqOV.o:(.bss+0x0): first defined here
/usr/bin/ld: lib/lib.a(InitializeHeaders.o):(.bss+0x3a980): multiple definition of `FileHeaderContents'; /tmp/ccpIOqOV.o:(.bss+0x3a980): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:58: Bin2AsciiLevel1.e] Error 1
make: Leaving directory '/home/user_name/grace-data-master/software/RELEASE_2010-03-31'
```
Apparently the problem is with these lines in the files 'GRACEbj_iolib.h' and 'GRACEiolib.h':
```
/* Define Global Header Label and contens arrays  */

EXTERN int8_t FileHeaderLabel[NFILETYPEMAX][NMAXHEADERREC][HEADERMAXCHAR];
EXTERN int8_t FileHeaderContents[NFILETYPEMAX][NMAXHEADERREC][HEADERMAXCHAR];
```
My PC configuration is:
```
$ gcc --version
gcc (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0

$ lsb_release -a

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal

$ make --version
GNU Make 4.2.1
Built for x86_64-pc-linux-gnu

```

Hope you can help me.
Thank you very much in advance!
Santiago.

**Comment by jgte** [comment]
Hello Santiago,

This is a compilation problem and from your gcc and make versions, it's not clear the reason. 

I suggest you rename the `RELEASE_2010-03-31` directory (e.g. into `RELEASE_2010-03-31.old`) and re-extract the contents of the `GraceReadSW_L1_2010-03-31.tar.gz` file. You'll get a fresh copy of the code in a new `RELEASE_2010-03-31` directory. Go into a new directory and try to compile that directly. You'll run into trouble because there's a few things that need to be changed. These changes are implemented in the `update.sh` script but possibly that's not working for you for some reason. Check the `README` file (that comes with the code) or diff the contents of the `RELEASE_2010-03-31` and `RELEASE_2010-03-31.old` directories to see what needs to be changed. 

Good luck, I hope this helps.

**Comment by ishusain** [comment]
Thank you very much for the suggestions, Joao.
Certainly you were correct, it was an issue with my gcc compiler version, so I downgraded to 
`gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0`
and it compiled correctly.

Best regards,
Santiago.
